setwd("~/Project")
library("tidyverse")
rawdata <- read.csv("Full Data.csv", stringsAsFactors = T)
bnflist <- read.csv("BNF List.csv", stringsAsFactors = T)
patientdetails <- unique( rawdata[,c(1, 2, 3, 4, 5)] )
patientmeds <- unique( rawdata[,c(1, 7)] )
patientconditions <- merge(patientmeds, bnflist)
patientprofile <- merge(patientconditions, patientdetails)
patientprofile2 <- unique( patientprofile[,c(1, 3, 5, 6, 7, 8)] )
processeddata <- patientprofile2 %>%
mutate(ind = 1) %>%
spread(BNF.Code, ind, fill = 0L)
bnfcodes <- unique( bnflist[,c(1, 2)] )
bnfcodelist <- t(bnfcodes)
colnames(bnfcodelist) = bnfcodelist[1, ]
allbnfcodes <- bnfcodelist[-c(1,2), ]
patientcount <- nrow(patientdetails)
bnfpatientlist <- data.frame(allbnfcodes)
bnfpatientlist[nrow(bnfpatientlist)+patientcount,] <- NA
bnfpatientlist <- merge(bnfpatientlist, patientdetails)
bnfpatientlist <- unique(bnfpatientlist)
processeddata2 <- data.frame(processeddata)
bnfpatientlist$X1.1X <- ifelse(is.na(bnfpatientlist$X1.1X) == TRUE, processeddata2$X1.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X1.2X <- ifelse(is.na(bnfpatientlist$X1.2X) == TRUE, processeddata2$X1.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X1.3X <- ifelse(is.na(bnfpatientlist$X1.3X) == TRUE, processeddata2$X1.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X1.4X <- ifelse(is.na(bnfpatientlist$X1.4X) == TRUE, processeddata2$X1.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X1.5X <- ifelse(is.na(bnfpatientlist$X1.5X) == TRUE, processeddata2$X1.5X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X1.6X <- ifelse(is.na(bnfpatientlist$X1.6X) == TRUE, processeddata2$X1.6X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X1.7X <- ifelse(is.na(bnfpatientlist$X1.7X) == TRUE, processeddata2$X1.7X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X1.8X <- ifelse(is.na(bnfpatientlist$X1.8X) == TRUE, processeddata2$X1.8X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X1.9X <- ifelse(is.na(bnfpatientlist$X1.9X) == TRUE, processeddata2$X1.9X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.1X <- ifelse(is.na(bnfpatientlist$X2.1X) == TRUE, processeddata2$X2.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.2X <- ifelse(is.na(bnfpatientlist$X2.2X) == TRUE, processeddata2$X2.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.3X <- ifelse(is.na(bnfpatientlist$X2.3X) == TRUE, processeddata2$X2.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.4X <- ifelse(is.na(bnfpatientlist$X2.4X) == TRUE, processeddata2$X2.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.5X <- ifelse(is.na(bnfpatientlist$X2.5X) == TRUE, processeddata2$X2.5X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.6X <- ifelse(is.na(bnfpatientlist$X2.6X) == TRUE, processeddata2$X2.6X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.8X <- ifelse(is.na(bnfpatientlist$X2.8X) == TRUE, processeddata2$X2.8X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.9X <- ifelse(is.na(bnfpatientlist$X2.9X) == TRUE, processeddata2$X2.9X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.11X <- ifelse(is.na(bnfpatientlist$X2.11X) == TRUE, processeddata2$X2.11X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X2.12X <- ifelse(is.na(bnfpatientlist$X2.12X) == TRUE, processeddata2$X2.12X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X3.1X <- ifelse(is.na(bnfpatientlist$X3.1X) == TRUE, processeddata2$X3.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X3.2X <- ifelse(is.na(bnfpatientlist$X3.2X) == TRUE, processeddata2$X3.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X3.3X <- ifelse(is.na(bnfpatientlist$X3.3X) == TRUE, processeddata2$X3.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X3.4X <- ifelse(is.na(bnfpatientlist$X3.4X) == TRUE, processeddata2$X3.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X3.7X <- ifelse(is.na(bnfpatientlist$X3.7X) == TRUE, processeddata2$X3.7X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X3.9X <- ifelse(is.na(bnfpatientlist$X3.9X) == TRUE, processeddata2$X3.9X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.1X <- ifelse(is.na(bnfpatientlist$X4.1X) == TRUE, processeddata2$X4.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.2X <- ifelse(is.na(bnfpatientlist$X4.2X) == TRUE, processeddata2$X4.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.3X <- ifelse(is.na(bnfpatientlist$X4.3X) == TRUE, processeddata2$X4.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.4X <- ifelse(is.na(bnfpatientlist$X4.4X) == TRUE, processeddata2$X4.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.5X <- ifelse(is.na(bnfpatientlist$X4.5X) == TRUE, processeddata2$X4.5X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.6X <- ifelse(is.na(bnfpatientlist$X4.6X) == TRUE, processeddata2$X4.6X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.7X <- ifelse(is.na(bnfpatientlist$X4.7X) == TRUE, processeddata2$X4.7X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.8X <- ifelse(is.na(bnfpatientlist$X4.8X) == TRUE, processeddata2$X4.8X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.9X <- ifelse(is.na(bnfpatientlist$X4.9X) == TRUE, processeddata2$X4.9X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.10X <- ifelse(is.na(bnfpatientlist$X4.10X) == TRUE, processeddata2$X4.10X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X4.11X <- ifelse(is.na(bnfpatientlist$X4.11X) == TRUE, processeddata2$X4.11X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X5.1X <- ifelse(is.na(bnfpatientlist$X5.1X) == TRUE, processeddata2$X5.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X5.2X <- ifelse(is.na(bnfpatientlist$X5.2X) == TRUE, processeddata2$X5.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X5.3X <- ifelse(is.na(bnfpatientlist$X5.3X) == TRUE, processeddata2$X5.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X5.4X <- ifelse(is.na(bnfpatientlist$X5.4X) == TRUE, processeddata2$X5.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X5.5X <- ifelse(is.na(bnfpatientlist$X5.5X) == TRUE, processeddata2$X5.5X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X6.1X <- ifelse(is.na(bnfpatientlist$X6.1X) == TRUE, processeddata2$X6.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X6.2X <- ifelse(is.na(bnfpatientlist$X6.2X) == TRUE, processeddata2$X6.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X6.3X <- ifelse(is.na(bnfpatientlist$X6.3X) == TRUE, processeddata2$X6.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X6.4X <- ifelse(is.na(bnfpatientlist$X6.4X) == TRUE, processeddata2$X6.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X6.5X <- ifelse(is.na(bnfpatientlist$X6.5X) == TRUE, processeddata2$X6.5X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X6.6X <- ifelse(is.na(bnfpatientlist$X6.6X) == TRUE, processeddata2$X6.6X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X6.7X <- ifelse(is.na(bnfpatientlist$X6.7X) == TRUE, processeddata2$X6.7X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X7.1X <- ifelse(is.na(bnfpatientlist$X7.1X) == TRUE, processeddata2$X7.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X7.2X <- ifelse(is.na(bnfpatientlist$X7.2X) == TRUE, processeddata2$X7.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X7.3X <- ifelse(is.na(bnfpatientlist$X7.3X) == TRUE, processeddata2$X7.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X7.4X <- ifelse(is.na(bnfpatientlist$X7.4X) == TRUE, processeddata2$X7.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X8.1X <- ifelse(is.na(bnfpatientlist$X8.1X) == TRUE, processeddata2$X8.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X8.2X <- ifelse(is.na(bnfpatientlist$X8.2X) == TRUE, processeddata2$X8.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X8.3X <- ifelse(is.na(bnfpatientlist$X8.3X) == TRUE, processeddata2$X8.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X9.1X <- ifelse(is.na(bnfpatientlist$X9.1X) == TRUE, processeddata2$X9.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X9.2X <- ifelse(is.na(bnfpatientlist$X9.2X) == TRUE, processeddata2$X9.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X9.3X <- ifelse(is.na(bnfpatientlist$X9.3X) == TRUE, processeddata2$X9.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X9.4X <- ifelse(is.na(bnfpatientlist$X9.4X) == TRUE, processeddata2$X9.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X9.5X <- ifelse(is.na(bnfpatientlist$X9.5X) == TRUE, processeddata2$X9.5X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X9.6X <- ifelse(is.na(bnfpatientlist$X9.6X) == TRUE, processeddata2$X9.6X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X9.7X <- ifelse(is.na(bnfpatientlist$X9.7X) == TRUE, processeddata2$X9.7X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X10.1X <- ifelse(is.na(bnfpatientlist$X10.1X) == TRUE, processeddata2$X10.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X10.2X <- ifelse(is.na(bnfpatientlist$X10.2X) == TRUE, processeddata2$X10.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X10.3X <- ifelse(is.na(bnfpatientlist$X10.3X) == TRUE, processeddata2$X10.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X11.3X <- ifelse(is.na(bnfpatientlist$X11.3X) == TRUE, processeddata2$X11.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X11.4X <- ifelse(is.na(bnfpatientlist$X11.4X) == TRUE, processeddata2$X11.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X11.5X <- ifelse(is.na(bnfpatientlist$X11.5X) == TRUE, processeddata2$X11.5X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X11.6X <- ifelse(is.na(bnfpatientlist$X11.6X) == TRUE, processeddata2$X11.6X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X11.7X <- ifelse(is.na(bnfpatientlist$X11.7X) == TRUE, processeddata2$X11.7X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X11.8X <- ifelse(is.na(bnfpatientlist$X11.8X) == TRUE, processeddata2$X11.8X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X12.1X <- ifelse(is.na(bnfpatientlist$X12.1X) == TRUE, processeddata2$X12.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X12.2X <- ifelse(is.na(bnfpatientlist$X12.2X) == TRUE, processeddata2$X12.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X12.3X <- ifelse(is.na(bnfpatientlist$X12.3X) == TRUE, processeddata2$X12.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.2X <- ifelse(is.na(bnfpatientlist$X13.2X) == TRUE, processeddata2$X13.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.3X <- ifelse(is.na(bnfpatientlist$X13.3X) == TRUE, processeddata2$X13.3X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.4X <- ifelse(is.na(bnfpatientlist$X13.4X) == TRUE, processeddata2$X13.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.5X <- ifelse(is.na(bnfpatientlist$X13.5X) == TRUE, processeddata2$X13.5X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.6X <- ifelse(is.na(bnfpatientlist$X13.6X) == TRUE, processeddata2$X13.6X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.7X <- ifelse(is.na(bnfpatientlist$X13.7X) == TRUE, processeddata2$X13.7X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.8X <- ifelse(is.na(bnfpatientlist$X13.8X) == TRUE, processeddata2$X13.8X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.9X <- ifelse(is.na(bnfpatientlist$X13.9X) == TRUE, processeddata2$X13.9X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.10X <- ifelse(is.na(bnfpatientlist$X13.10X) == TRUE, processeddata2$X13.10X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.11X <- ifelse(is.na(bnfpatientlist$X13.11X) == TRUE, processeddata2$X13.11X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X13.12X <- ifelse(is.na(bnfpatientlist$X13.12X) == TRUE, processeddata2$X13.12X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X14.4X <- ifelse(is.na(bnfpatientlist$X14.4X) == TRUE, processeddata2$X14.4X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X15.1X <- ifelse(is.na(bnfpatientlist$X15.1X) == TRUE, processeddata2$X15.1X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
bnfpatientlist$X15.2X <- ifelse(is.na(bnfpatientlist$X15.2X) == TRUE, processeddata2$X15.2X[processeddata2$Patient.Number %in% bnfpatientlist$Patient.Number], NA)
finaldata <- bnfpatientlist[,c(89,90,91,92,93,1:ncol(bnfcodelist))]
setwd("~/Project/ETL")
write.csv(finaldata, file = "MLData.csv", row.names = F)
MLData <- read.csv("MLData.csv", stringsAsFactors = T)
MLData[is.na(MLData)] <- 0
MLData$Sex<- ifelse(MLData$Sex=="M", 1, 0)
MLDataTrimmed <- MLData[,c(5, 4, 11, 12, 14, 15, 16, 19, 24, 47)]
names(MLDataTrimmed) <- c("Age", "Sex", "X1.6", "X1.7", "X1.9", "X2.1", "X2.2", "X2.5", "X2.12", "X6.1")
write.csv(MLDataTrimmed, file = "RFTraining.csv", row.names = FALSE)
write.csv(MLDataTrimmed, file = "ANNTraining.csv", row.names = FALSE)